vich_uploader:
    db_driver: orm

    mappings:
        cover_image:
            uri_prefix: /img/covers
            upload_destination: '%kernel.project_dir%/public/img/covers'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
